-- Flyway migration: create initial schema for Kamion
CREATE TABLE IF NOT EXISTS kamion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spz VARCHAR(255) NOT NULL UNIQUE,
    znacka VARCHAR(255) NOT NULL,
    nosnost_kg INTEGER NOT NULL
);

-- Create sequence expected by Hibernate validation
-- H2 is case-insensitive for unquoted identifiers; name chosen to match message: kamion_SEQ
CREATE SEQUENCE IF NOT EXISTS kamion_SEQ START WITH 1 INCREMENT BY 1;